import './modules/root_and_dark_light_mode.css';
import './modules/type-scale/index.css';
import './modules/typography/index.css';
import './modules/layout/index.css';
import './modules/align/index.css';
import './modules/margin/index.css';
import './modules/padding/index.css';
import './modules/grid/index.css';
import './modules/flexbox/index.css';
import './modules/position/index.css';
import './modules/border/index.css';
import './modules/hide/index.css';
import './modules/picnic/picnic.css';
import './modules/mrmrs-colors/colors.css';
console.info('Ok');